// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgGZLB6o1CtArTAAY4rLc9CWDzZNHxe48',
    appId: '1:224375229493:web:9f44833af3470b6ba7f57c',
    messagingSenderId: '224375229493',
    projectId: 'b2bmvp-ffd60',
    authDomain: 'b2bmvp-ffd60.firebaseapp.com',
    storageBucket: 'b2bmvp-ffd60.appspot.com',
    measurementId: 'G-SJ47W9FKGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYZuX2RIuaxQPEYLBivK_7pLuAgs9aVKY',
    appId: '1:224375229493:android:f6d69d0e995758e4a7f57c',
    messagingSenderId: '224375229493',
    projectId: 'b2bmvp-ffd60',
    storageBucket: 'b2bmvp-ffd60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnx1SdMQYhtZrD113WbzYYZIyb1KLY4is',
    appId: '1:224375229493:ios:96d03f68d525024fa7f57c',
    messagingSenderId: '224375229493',
    projectId: 'b2bmvp-ffd60',
    storageBucket: 'b2bmvp-ffd60.appspot.com',
    iosClientId: '224375229493-hl7gtcc1srbolmtpe61340ofc9bhof0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.b2bMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnx1SdMQYhtZrD113WbzYYZIyb1KLY4is',
    appId: '1:224375229493:ios:f44cfd091787dbe5a7f57c',
    messagingSenderId: '224375229493',
    projectId: 'b2bmvp-ffd60',
    storageBucket: 'b2bmvp-ffd60.appspot.com',
    iosClientId: '224375229493-cstiojupvqaqgpnvs56hlvrclhbme4g0.apps.googleusercontent.com',
    iosBundleId: 'com.example.b2bMvp.RunnerTests',
  );
}
